url: https://courses.stolley.co
baseurl: /rtc/

timezone: America/Chicago

course:
  number: ITMD 469/545
  title: Web Real-Time Communications
  uid: rtc
  tagline: >
    A course in browser-to-browser real-time communication and data exchange.
  term: Fall 2020
  # Set `days: ""` (empty string) for weekly/asynchronous classes
  days:
    - Monday
    - Wednesday

  license:
    name: Creative Commons
    url: https://creativecommons.org/licenses/by/4.0/
  instructor:
    honorific: Dr.
    name: Karl Stolley
    title: Professor
    full_title: Associate Professor of Information Technology and Management
    url: https://stolley.co/
    github: https://github.com/karlstolley/
    email: kstolley@iit.edu
    office_hours: >
      Office hours via Basecamp Chat or Pings on Tuesdays, 4pm to 5pm Central Time
      (America/Chicago), or by appointment or chance. If you’d like to audio or video chat, we can
      of course do that, too. Just message me first. I’m always signed into Basecamp and closely
      monitor my notifications. Message or email any time—I make students a priority, and I will
      respond as soon as I am able.
  navigation:
    - label: Calendar
      href: "#this-week"
      id: cal
    - label: Basecamp
      href: "https://launchpad.37signals.com/signin"
      id: bcp
    - label: Demos
      href: "https://github.com/rtc-2020"
      id: dmo
    - label: Projects
      href: "projects/#current"
      id: pro
    - label: Policies
      href: "policies/"
      id: pol
  css:
    font-url: "https://use.typekit.net/qqk1feg.css"

collections_dir: syllabus

collections:
  weeks:
  projects:
  policies:
    # Rearrange the files listed here to change their order on the policies page.
    # To remove a section from the policies page, you *must* delete the file in the
    # /syllabus/_policies/ directory
    order:
      - description.md
      - goals.md
      - outcomes.md
      - objectives.md
      - books.md
      - materials.md
      - special-needs.md
      - participation.md
      - assignment-submission.md
      - late-work.md
      - grading-policy.md
      - grading-criteria.md
      - technology-policy.md
      - academic-integrity.md

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-open-course

exclude:
  - backstop_data
  - backstop.json
  - exe
  - lib
  - Rakefile
  - "*.gemspec"
